// Copyright (c) 2014-2016 The Bitcoin Core developers
// Copyright (c) 2019-2020 IsotopeC Development Labs
#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * Contributers:
 * Wladimir J. van der Laan AKA: laanwj on Aug 3, 2014
 * Michael AKA: fanquake on Oct 25, 2014
 * paveljanik on Nov 3, 2014
 * Pieter Wuille AKA: sipa on Dec 23, 2014
 *
 * Banned nodes
 * The set of banned nodes is in setBanned in net.cpp
 *
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {

};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
